// scripts/batch14_extra.cjs
const steamCover = (appId) => `https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/${appId}/header.jpg`;

const NEW_GAMES = [
  {
    id: 'splinter-cell-chaos-theory',
    title: 'Tom Clancy\'s Splinter Cell Chaos Theory',
    category: ['stealth', 'action_fps', 'retro'],
    platform: 'PC',
    rating: 9.9,
    year: 2005,
    coverUrl: steamCover('13570'),
    description: 'Sam Fisher no ápice absoluto da espionagem tática com visor térmico, faca de combate e a trilha de Amon Tobin.',
    timeToBeat: { main: 11, extra: 14, completionist: 20 }
  },
  {
    id: 'splinter-cell-blacklist',
    title: 'Tom Clancy\'s Splinter Cell Blacklist',
    category: ['stealth', 'action_fps'],
    platform: 'PC',
    rating: 9.3,
    year: 2013,
    coverUrl: steamCover('235600'),
    description: 'Comande o avião cargueiro Paladin como líder da Fourth Echelon alternando estilos Ghost, Panther e Assault.',
    timeToBeat: { main: 12, extra: 21, completionist: 38 }
  },
  {
    id: 'hitman-world-of-assassination',
    title: 'HITMAN World of Assassination',
    category: ['stealth'],
    platform: 'PC',
    rating: 9.8,
    year: 2021,
    coverUrl: steamCover('1659040'),
    description: 'O Agente 47 na trilogia moderna completa: disfarces perfeitos, assassinatos criativos em Paris, Sapienza, Miami e Dubai.',
    timeToBeat: { main: 30, extra: 75, completionist: 180 }
  },
  {
    id: 'hitman-blood-money',
    title: 'Hitman: Blood Money',
    category: ['stealth', 'ps2', 'retro'],
    platform: 'PC',
    rating: 9.7,
    year: 2006,
    coverUrl: steamCover('6860'),
    description: 'O clássico onde cada morte pode parecer um infeliz acidente: Ave Maria no funeral e missões inesquecíveis como A New Life.',
    timeToBeat: { main: 13, extra: 18, completionist: 28 }
  },
  {
    id: 'deus-ex-human-revolution',
    title: 'Deus Ex: Human Revolution - Director\'s Cut',
    category: ['scifi', 'stealth', 'action_fps', 'rpg'],
    platform: 'PC',
    rating: 9.6,
    year: 2013,
    coverUrl: steamCover('238010'),
    description: 'Adam Jensen em Detroit 2027 com aprimoramentos cibernéticos mecânicos: "I never asked for this".',
    timeToBeat: { main: 18, extra: 29, completionist: 45 }
  },
  {
    id: 'deus-ex-mankind-divided',
    title: 'Deus Ex: Mankind Divided',
    category: ['scifi', 'stealth', 'action_fps', 'rpg'],
    platform: 'PC',
    rating: 9.2,
    year: 2016,
    coverUrl: steamCover('337000'),
    description: 'O Apartheid Mecânico na Praga cyberpunk de 2029 com o Titã de armadura dermal e o disparo de lâminas Nanoblade.',
    timeToBeat: { main: 16, extra: 30, completionist: 50 }
  },
  {
    id: 'dishonored-2',
    title: 'Dishonored 2',
    category: ['stealth', 'action_fps'],
    platform: 'PC',
    rating: 9.7,
    year: 2016,
    coverUrl: steamCover('403640'),
    description: 'Jogue como Emily Kaldwin ou Corvo na ensolarada e decadente cidade costeira de Karnaca com a mansão mecânica Clockwork Mansion.',
    timeToBeat: { main: 13, extra: 21, completionist: 45 }
  },
  {
    id: 'deathloop',
    title: 'DEATHLOOP',
    category: ['action_fps', 'scifi'],
    platform: 'PC',
    rating: 9.3,
    year: 2021,
    coverUrl: steamCover('1252330'),
    description: 'Colt precisa assassinar 8 visionários na ilha retrô dos anos 60 de Blackreef em um único dia antes do loop resetar à meia-noite.',
    timeToBeat: { main: 16, extra: 26, completionist: 38 }
  },
  {
    id: 'sifu-game',
    title: 'Sifu',
    category: ['fighting', 'hackslash', 'action_fps'],
    platform: 'PC',
    rating: 9.7,
    year: 2022,
    coverUrl: steamCover('2138710'),
    description: 'Kung Fu Pak Mei autêntico com um amuleto mágico que envelhece seu lutador a cada morte: domine as esquivas ou morra de velhice.',
    timeToBeat: { main: 10, extra: 16, completionist: 28 }
  },
  {
    id: 'ghostrunner-1',
    title: 'Ghostrunner',
    category: ['action_fps', 'scifi', 'platformer'],
    platform: 'PC',
    rating: 9.5,
    year: 2020,
    coverUrl: steamCover('1144460'),
    description: 'Ninja cibernético correndo pelas paredes em alta velocidade na Torre Dharma onde um único acerto mata tanto você quanto o inimigo.',
    timeToBeat: { main: 7, extra: 11, completionist: 18 }
  },
  {
    id: 'ghostrunner-2',
    title: 'Ghostrunner 2',
    category: ['action_fps', 'scifi', 'platformer'],
    platform: 'PC',
    rating: 9.4,
    year: 2023,
    coverUrl: steamCover('2144740'),
    description: 'Jack ganha uma moto veloz com combate veicular armado além de novos poderes shuriken e bloqueio perfeito de katana.',
    timeToBeat: { main: 9, extra: 14, completionist: 22 }
  },
  {
    id: 'mirrors-edge-original',
    title: "Mirror's Edge",
    category: ['platformer', 'action_fps'],
    platform: 'PC',
    rating: 9.3,
    year: 2008,
    coverUrl: steamCover('17410'),
    description: 'Faith Connors corre pelos telhados brancos imaculados de uma cidade totalitária no primeiro jogo autêntico de parkour em primeira pessoa.',
    timeToBeat: { main: 6, extra: 9, completionist: 15 }
  },
  {
    id: 'kingdom-come-deliverance',
    title: 'Kingdom Come: Deliverance',
    category: ['rpg', 'openworld'],
    platform: 'PC',
    rating: 9.5,
    year: 2018,
    coverUrl: steamCover('379430'),
    description: 'O filho do ferreiro Henry na Boêmia medieval de 1403: hiper-realismo histórico, esgrima técnica de 5 direções e fome real.',
    timeToBeat: { main: 41, extra: 82, completionist: 130 }
  },
  {
    id: 'mount-and-blade-2-bannerlord',
    title: 'Mount & Blade II: Bannerlord',
    category: ['rpg', 'openworld', 'action_fps'],
    platform: 'PC',
    rating: 9.4,
    year: 2022,
    coverUrl: steamCover('261550'),
    description: 'Comande centenas de soldados em tempo real em cercos de castelos colossais em Calradia fundando sua própria dinastia real.',
    timeToBeat: { main: 45, extra: 110, completionist: 250 }
  },
  {
    id: 'age-of-empires-2-de',
    title: 'Age of Empires II: Definitive Edition',
    category: ['retro'],
    platform: 'PC',
    rating: 9.9,
    year: 2019,
    coverUrl: steamCover('813780'),
    description: 'Wololo! O clássico supremo dos jogos de estratégia em tempo real remasterizado em 4K com mais de 40 civilizações históricas.',
    timeToBeat: { main: 45, extra: 120, completionist: 300 }
  },
  {
    id: 'age-of-empires-4',
    title: 'Age of Empires IV',
    category: [],
    platform: 'PC',
    rating: 9.3,
    year: 2021,
    coverUrl: steamCover('1466860'),
    description: 'Documentários históricos integrados e civilizações altamente assimétricas como os Mongóis que desmontam cidades inteiras.',
    timeToBeat: { main: 30, extra: 60, completionist: 150 }
  },
  {
    id: 'civilization-6',
    title: "Sid Meier's Civilization VI",
    category: [],
    platform: 'PC',
    rating: 9.6,
    year: 2016,
    coverUrl: steamCover('289070'),
    description: 'Só mais um turno! Guie sua civilização desde a Idade da Pedra até a Era Espacial desempacotando distritos no mapa.',
    timeToBeat: { main: 22, extra: 65, completionist: 250 }
  },
  {
    id: 'crusader-kings-3',
    title: 'Crusader Kings III',
    category: ['rpg'],
    platform: 'PC',
    rating: 9.6,
    year: 2020,
    coverUrl: steamCover('1158310'),
    description: 'A simulação dinástica da Idade Média: casamentos estratégicos, assassinatos de nobres rivais e intrigas na corte real.',
    timeToBeat: { main: 40, extra: 100, completionist: 300 }
  },
  {
    id: 'baldurs-gate-1-ee',
    title: "Baldur's Gate: Enhanced Edition",
    category: ['rpg', 'retro'],
    platform: 'PC',
    rating: 9.5,
    year: 2012,
    coverUrl: steamCover('228280'),
    description: 'O início da lenda de BioWare na Costa da Espada: saia de Candlekeep e investigue a misteriosa crise do ferro.',
    timeToBeat: { main: 31, extra: 50, completionist: 90 }
  },
  {
    id: 'baldurs-gate-2-ee',
    title: "Baldur's Gate II: Enhanced Edition",
    category: ['rpg', 'retro'],
    platform: 'PC',
    rating: 9.9,
    year: 2013,
    coverUrl: steamCover('257350'),
    description: 'Preso pelo arquimago Jon Irenicus na cidade de Athkatla: um dos maiores RPGs de Dungeons & Dragons já desenvolvidos.',
    timeToBeat: { main: 44, extra: 75, completionist: 140 }
  },
  {
    id: 'planescape-torment-ee',
    title: 'Planescape: Torment: Enhanced Edition',
    category: ['rpg', 'retro'],
    platform: 'PC',
    rating: 9.9,
    year: 2017,
    coverUrl: steamCover('466300'),
    description: 'The Nameless One acorda em um necrotério com uma caveira flutuante Morte: "What can change the nature of a man?".',
    timeToBeat: { main: 30, extra: 45, completionist: 60 }
  },
  {
    id: 'ace-attorney-trilogy',
    title: 'Phoenix Wright: Ace Attorney Trilogy',
    category: ['retro'],
    platform: 'PC',
    rating: 9.8,
    year: 2019,
    coverUrl: steamCover('787480'),
    description: 'OBJECTION! Grite nos tribunais, aponte contradições nos depoimentos das testemunhas e salve réus inocentes com Phoenix Wright.',
    timeToBeat: { main: 60, extra: 65, completionist: 75 }
  },
  {
    id: 'danganronpa-trigger-happy',
    title: 'Danganronpa: Trigger Happy Havoc',
    category: ['anime'],
    platform: 'PC',
    rating: 9.6,
    year: 2016,
    coverUrl: steamCover('413410'),
    description: 'O urso sádico Monokuma prende 15 estudantes prodígios na Hope\'s Peak Academy em um jogo mortal onde matar é a única rota de fuga.',
    timeToBeat: { main: 25, extra: 33, completionist: 50 }
  },
  {
    id: 'danganronpa-2-goodbye-despair',
    title: 'Danganronpa 2: Goodbye Despair',
    category: ['anime'],
    platform: 'PC',
    rating: 9.7,
    year: 2016,
    coverUrl: steamCover('413420'),
    description: 'Hajime Hinata e seus colegas na Ilha Jabberwock: debates acalorados no Class Trial e reviravoltas chocantes com Nagito Komaeda.',
    timeToBeat: { main: 32, extra: 43, completionist: 70 }
  },
  {
    id: 'enter-the-gungeon',
    title: 'Enter the Gungeon',
    category: ['indie', 'action_fps'],
    platform: 'PC',
    rating: 9.7,
    year: 2016,
    coverUrl: steamCover('311690'),
    description: 'Desça ao labirinto das balas para encontrar a Arma que Pode Matar o Passado em tiroteios bullet-hell com rolamento de esquiva.',
    timeToBeat: { main: 22, extra: 60, completionist: 140 }
  },
  {
    id: 'rogue-legacy-2',
    title: 'Rogue Legacy 2',
    category: ['indie', 'platformer', 'rpg'],
    platform: 'PC',
    rating: 9.6,
    year: 2022,
    coverUrl: steamCover('1253920'),
    description: 'Roguelite genealógico onde cada filho que herda a missão possui traços genéticos únicos como sinestesia, daltonismo ou gigantismo.',
    timeToBeat: { main: 28, extra: 50, completionist: 90 }
  },
  {
    id: 'risk-of-rain-2',
    title: 'Risk of Rain 2',
    category: ['indie', 'action_fps', 'scifi'],
    platform: 'PC',
    rating: 9.7,
    year: 2020,
    coverUrl: steamCover('632360'),
    description: 'Sobreviva no planeta alienígena Petrichor V onde a dificuldade sobe automaticamente a cada minuto acumulando itens infinitos.',
    timeToBeat: { main: 15, extra: 45, completionist: 100 }
  },
  {
    id: 'deep-rock-galactic',
    title: 'Deep Rock Galactic',
    category: ['indie', 'action_fps', 'scifi'],
    platform: 'PC',
    rating: 9.8,
    year: 2020,
    coverUrl: steamCover('548430'),
    description: 'Rock and Stone! 4 anões espaciais escavam cavernas 100% destrutíveis para minerar ouro e cerveja contra enxames de alienígenas.',
    timeToBeat: { main: 30, extra: 85, completionist: 300 }
  },
  {
    id: 'no-mans-sky',
    title: "No Man's Sky",
    category: ['scifi', 'openworld'],
    platform: 'PC',
    rating: 9.3,
    year: 2016,
    coverUrl: steamCover('275850'),
    description: '18 quintilhões de planetas procedurais: a maior redenção da história dos games com viagens interestelares contínuas e bases.',
    timeToBeat: { main: 35, extra: 80, completionist: 180 }
  },
  {
    id: 'dredge-indie',
    title: 'DREDGE',
    category: ['indie', 'horror'],
    platform: 'PC',
    rating: 9.6,
    year: 2023,
    coverUrl: steamCover('1562430'),
    description: 'Pilote seu barco pesqueiro por ilhas remotas pegando peixes e desenterrando terrores cósmicos lovecraftianos nas águas escuras.',
    timeToBeat: { main: 9, extra: 12, completionist: 17 }
  },
  {
    id: 'inscryption-indie',
    title: 'Inscryption',
    category: ['indie', 'horror'],
    platform: 'PC',
    rating: 9.8,
    year: 2021,
    coverUrl: steamCover('1092790'),
    description: 'Um jogo de cartas sombrio em uma cabana que se transforma em uma das metanarrativas mais geniais de Daniel Mullins.',
    timeToBeat: { main: 12, extra: 16, completionist: 23 }
  },
  {
    id: 'neon-white',
    title: 'Neon White',
    category: ['indie', 'action_fps', 'platformer'],
    platform: 'PC',
    rating: 9.7,
    year: 2022,
    coverUrl: steamCover('1533420'),
    description: 'Assassinos do Inferno competem por uma vaga no Céu em fases de speedrun milimétrico descartando cartas de armas para pular.',
    timeToBeat: { main: 11, extra: 17, completionist: 28 }
  },
  {
    id: 'ultrakill',
    title: 'ULTRAKILL',
    category: ['indie', 'action_fps', 'retro'],
    platform: 'PC',
    rating: 9.9,
    year: 2020,
    coverUrl: steamCover('1229490'),
    description: 'MANKIND IS DEAD. BLOOD IS FUEL. HELL IS FULL. O boomer-shooter mais veloz do mundo onde você se cura absorvendo sangue fresco.',
    timeToBeat: { main: 8, extra: 15, completionist: 35 }
  },
  {
    id: 'spelunky-2',
    title: 'Spelunky 2',
    category: ['indie', 'platformer'],
    platform: 'PC',
    rating: 9.6,
    year: 2020,
    coverUrl: steamCover('418530'),
    description: 'Ana Spelunky viaja até a Lua explorando cavernas procedurais mortais onde qualquer erro milimétrico desencadeia uma reação em cadeia.',
    timeToBeat: { main: 25, extra: 60, completionist: 140 }
  },
  {
    id: 'warframe',
    title: 'Warframe',
    category: ['scifi', 'action_fps', 'hackslash'],
    platform: 'PC',
    rating: 9.5,
    year: 2013,
    coverUrl: steamCover('230410'),
    description: 'Ninjas espaciais biomotores despertados pelo Lotus com acrobacias acrobáticas em alta velocidade e centenas de armas no Sistema Solar.',
    timeToBeat: { main: 60, extra: 200, completionist: 1000 }
  },
  {
    id: 'path-of-exile',
    title: 'Path of Exile',
    category: ['rpg', 'hackslash'],
    platform: 'PC',
    rating: 9.6,
    year: 2013,
    coverUrl: steamCover('238960'),
    description: 'Exilado no continente sombrio de Wraeclast com a lendária árvore passiva gigante com mais de 1300 nós interconectados.',
    timeToBeat: { main: 35, extra: 85, completionist: 450 }
  },
  {
    id: 'the-witcher-1-enhanced',
    title: 'The Witcher: Enhanced Edition',
    category: ['rpg'],
    platform: 'PC',
    rating: 8.9,
    year: 2008,
    coverUrl: steamCover('20900'),
    description: 'Geralt de Rivia amnésico em Vizima combate a Salamandra no jogo que deu origem à aclamada trilogia da CD Projekt Red.',
    timeToBeat: { main: 36, extra: 45, completionist: 63 }
  },
  {
    id: 'the-witcher-2-assassins-of-kings',
    title: 'The Witcher 2: Assassins of Kings Enhanced Edition',
    category: ['rpg'],
    platform: 'PC',
    rating: 9.4,
    year: 2011,
    coverUrl: steamCover('20920'),
    description: 'Geralt é acusado de regicídio e caça Letho de Gulet com duas ramificações de campanha inteiramente diferentes nos Atos 2 e 3.',
    timeToBeat: { main: 24, extra: 35, completionist: 55 }
  },
  {
    id: 'bioshock-2-remastered',
    title: 'BioShock 2 Remastered',
    category: ['action_fps', 'scifi', 'horror'],
    platform: 'PC',
    rating: 9.3,
    year: 2016,
    coverUrl: steamCover('409720'),
    description: 'Jogue como o protótipo Subject Delta (Big Daddy) com broca gigante e furadeira dupla contra a psicóloga Sofia Lamb e as Big Sisters.',
    timeToBeat: { main: 11, extra: 15, completionist: 23 }
  },
  {
    id: 'wolfenstein-the-old-blood',
    title: 'Wolfenstein: The Old Blood',
    category: ['action_fps'],
    platform: 'PC',
    rating: 9.1,
    year: 2015,
    coverUrl: steamCover('350080'),
    description: 'Infiltre-se no Castelo Wolfenstein nos Alpes Bávaros armado com canos de ferro escaláveis contra zumbis ocultistas da SS.',
    timeToBeat: { main: 6, extra: 9, completionist: 16 }
  },
  {
    id: 'guacamelee-2',
    title: 'Guacamelee! 2',
    category: ['platformer', 'indie'],
    platform: 'PC',
    rating: 9.4,
    year: 2018,
    coverUrl: steamCover('534550'),
    description: 'Juan Aguacate volta do retiro para salvar o Mexiverse com golpes de Lucha Libre e a transformação bizarra em frango guerreiro.',
    timeToBeat: { main: 9, extra: 13, completionist: 18 }
  },
  {
    id: 'dust-an-elysian-tail',
    title: 'Dust: An Elysian Tail',
    category: ['hackslash', 'platformer', 'indie', 'rpg'],
    platform: 'PC',
    rating: 9.3,
    year: 2012,
    coverUrl: steamCover('236090'),
    description: 'Dust e a espada falante Ahrah cortam centenas de monstros em combos aéreos rotativos espetaculares animados à mão.',
    timeToBeat: { main: 10, extra: 14, completionist: 20 }
  },
  {
    id: 'nuclear-throne',
    title: 'Nuclear Throne',
    category: ['indie', 'action_fps', 'retro'],
    platform: 'PC',
    rating: 9.4,
    year: 2015,
    coverUrl: steamCover('242680'),
    description: 'O roguelike pós-apocalíptico da Vlambeer onde mutantes lutam com escopetas triplas para alcançar o Trono Nuclear.',
    timeToBeat: { main: 11, extra: 30, completionist: 90 }
  },
  {
    id: 'bomb-rush-cyberfunk',
    title: 'Bomb Rush Cyberfunk',
    category: ['platformer', 'indie'],
    platform: 'PC',
    rating: 9.5,
    year: 2023,
    coverUrl: steamCover('1353230'),
    description: 'O sucessor espiritual de Jet Set Radio: patine com grafite, dança breakbeat e trilha sonora hip-hop de Hideki Naganuma.',
    timeToBeat: { main: 11, extra: 17, completionist: 25 }
  },
  {
    id: 'core-keeper',
    title: 'Core Keeper',
    category: ['indie', 'rpg', 'openworld'],
    platform: 'PC',
    rating: 9.4,
    year: 2024,
    coverUrl: steamCover('1621690'),
    description: 'Aventura mineradora subterrânea para até 8 jogadores combinando mineração de Terraria com agricultura de Stardew Valley.',
    timeToBeat: { main: 30, extra: 60, completionist: 100 }
  },
  {
    id: 'quakere-remastered',
    title: 'Quake II',
    category: ['action_fps', 'scifi', 'retro'],
    platform: 'PC',
    rating: 9.5,
    year: 2023,
    coverUrl: steamCover('2320'),
    description: 'A invasão do planeta alienígena Stroggos com Railgun, Super Shotgun e a trilha industrial estrondosa de Sonic Mayhem.',
    timeToBeat: { main: 8, extra: 13, completionist: 20 }
  },
  {
    id: 'fallout-1-retro',
    title: 'Fallout: A Post Nuclear Role Playing Game',
    category: ['fallout', 'rpg', 'retro'],
    platform: 'PC',
    rating: 9.5,
    year: 1997,
    coverUrl: steamCover('38400'),
    description: 'Onde tudo começou: saia do Vault 13 para encontrar o Water Chip em um RPG isométrico pioneiro com o sistema S.P.E.C.I.A.L.',
    timeToBeat: { main: 16, extra: 23, completionist: 33 }
  },
  {
    id: 'fallout-2-retro',
    title: 'Fallout 2',
    category: ['fallout', 'rpg', 'retro'],
    platform: 'PC',
    rating: 9.7,
    year: 1998,
    coverUrl: steamCover('38410'),
    description: 'O Escolhido (Chosen One) da tribo Arroyo busca o G.E.C.K. e enfrenta a Enclave em New Reno, Vault City e San Francisco.',
    timeToBeat: { main: 31, extra: 48, completionist: 75 }
  },
  {
    id: 'tiny-tinas-wonderlands',
    title: "Tiny Tina's Wonderlands",
    category: ['action_fps', 'rpg'],
    platform: 'PC',
    rating: 9.0,
    year: 2022,
    coverUrl: steamCover('1286680'),
    description: 'A caótica Tiny Tina mestra uma sessão de RPG de mesa (Bunkers & Badasses) onde armas atiram magia e feitiços.',
    timeToBeat: { main: 16, extra: 30, completionist: 60 }
  },
  {
    id: 'wasteland-3',
    title: 'Wasteland 3',
    category: ['rpg'],
    platform: 'PC',
    rating: 9.4,
    year: 2020,
    coverUrl: steamCover('719040'),
    description: 'Rangers do Deserto no Colorado congelado sob o comando do Patriarca em combates táticos em turnos profundos.',
    timeToBeat: { main: 37, extra: 58, completionist: 82 }
  }
];

console.log('Batch 14 (Extra) pronto com', NEW_GAMES.length, 'jogos.');
module.exports = { NEW_GAMES };
